_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
dropout_rate:
    value: 0.2
epochs:
    value: 10
hidden_layers:
    value:
        - 128
        - 64
learning_rate:
    value: 0.01
